name: docker-deploy

on:
  release:
    types: [published, created, edited]

jobs:
  testing-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Build container image
        run: |
          docker build -t quay.io/urlstechie/urlchecker .
          DOCKER_TAG=$(docker run quay.io/urlstechie/urlchecker --version)
          printf "Docker Tag is ${DOCKER_TAG}\n"
          echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
      - name: Docker login
        env:
          docker_user: ${{ secrets.DOCKER_USERNAME }}
          docker_pass: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u="${docker_user}" -p="${docker_pass}" quay.io
      - name: Push containers
        run: |
          docker tag quay.io/urlstechie/urlchecker:latest "quay.io/urlstechie/urlchecker:${DOCKER_TAG}"
          docker push quay.io/urlstechie/urlchecker:latest
          docker push "quay.io/urlstechie/urlchecker:${DOCKER_TAG}"

